### ISSUE TITLE
yarn test not working

### ISSUE THREAD

**Issue by pastor3llo** [react-workspaces/cra-workspaces-playground#4]
I tried the stuff in this repo but i found that yarn test is not working
` Test suite failed to run

    Cannot find module '@project/comp-one' from 'App.js'

      2 | import logo from './logo.svg';
      3 | import './App.css';
    > 4 | import CompOne from '@project/comp-one';
        | ^
      5 | 
      6 | class App extends Component {
      7 |     render() {

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (src/App.js:4:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.451s`

**Comment by F1LT3R** [comment]
Joe are you running the tests?

**Comment by pastor3llo** [comment]
i just took the repo as is and i did:
$ cd ~/repos/cra-workspaces-poc/apps/app-foo
$ yarn test

**Comment by Remimstr** [comment]
I have experienced the same behaviour both with my own monorepo and a clone of this one.

**Comment by Remimstr** [comment]
@F1LT3R this is a really big hurdle to me using this approach on my codebase. Is there anything I can do to help fix it?

**Comment by F1LT3R** [comment]
Should be working now @Remimstr @pastor3llo you want to checkout and test?

**Comment by Remimstr** [comment]
Unfortunately no, it's still not working. I did exactly the steps as you outlined for a new repo:
```
git clone git@github.com:react-workspaces/cra-workspaces-playground.git
cd cra-workspaces-playground
yarn
cd packages/apps/app/one
yarn test
```
and it still gives the same "Cannot find module '@project/comp-one' from 'App.js' error.

In case it's relevant, I'm using node v11.5.0 yarn v1.15.2 and npm v6.4.1

**Comment by alistair-hmh** [comment]
Working here...

<img width="678" alt="Screen Shot 2019-04-27 at 9 09 18 AM" src="https://user-images.githubusercontent.com/38665769/56850126-2d0db180-68cc-11e9-97fe-01996a02714c.png">

You might need to pull this repo and try that way.

I think following the steps there are parts missing that would make testing work for you.

**Comment by alistair-hmh** [comment]
@Remimstr try adding `"main": "src/index.js"` to each `package.json`.

**Comment by Remimstr** [comment]
That suggestion fixed it for me. Thank you for the help!
